export const simType = ['Single sim', 'Couple', 'Family', 'Roommates' ]
export const colourScheme = ['Boring beige', 'Neon', 'Earth tones', 'Beachy', 'Pastel', 'Jewel tones', 'Monochromatic', 'Neutral with a colour pop', 'Bold', 'High contrast']
export const typeOfBuild = ['Tiny home', 'Small home', 'Regular home', 'Large home', 'Mansion']
export const exteriorFeature = ['Pond', 'Garden', 'Pool', 'Patio', 'Porch', 'Driveway', 'Hot tub', 'Livestock', 'Shed', 'Garage', 'Water feature', 'Chimney', 'Picnic area', 'Craft area', 'BBQ area', 'Greenhouse', 'Play area']
export const buildingStyle = ['Contemporary', 'Mid-century', 'Cottage', 'Trailer', 'Art deco', 'Colonial', 'Suburban', 'Bungalow', 'Farmhouse', 'Craftsman', 'Georgian', 'Tudor', 'Victorian', 'Organic', 'Gothic', 'Queen Anne']
export const walls = ['Brick', 'Stone', 'Panelling', 'Siding', 'Shingles', 'Metal']
export const concept = ['Open', 'Closed']
export const bonusSpace = ['Storage room', 'Basement', 'Attic', 'Gym', 'Art studio', 'Game room', 'Guest room', 'Craft room', 'Laundry room', 'Library', 'Bar', 'Meditation space', 'Office', 'Music room', 'Play room']
